### ISSUE TITLE
Launch Tracker 🔴

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/rust#1095]
_This issue is part of the migration to v3. You can read full details about the various changes [here](https://github.com/exercism/v3-launch/)._

To get your track ready for Exercism v3, the following needs to be done:

- [x] [Configure online editor](https://github.com/exercism/rust/issues/1086)
- [x] [Add key features](https://github.com/exercism/rust/issues/1087)
- [x] [Add tags](https://github.com/exercism/rust/issues/1088)
- [ ] [Add prerequisites to Practice Exercises](https://github.com/exercism/rust/issues/1089)
- [x] [Update status of track](https://github.com/exercism/rust/issues/1093)
- [ ] [Update status of Concept Exercises](https://github.com/exercism/rust/issues/1094)
- [x] [Pass linting checks](https://github.com/exercism/rust/issues/1090)
- [x] [Build Test Runner](https://github.com/exercism/rust/issues/1091)
- [x] [Build Analyzer and Representer](https://github.com/exercism/rust/issues/1092) (optional)
- [x] [Add blurb to Concept Exercises](https://github.com/exercism/rust/issues/1185)

This issue may be automatically added to over time. While track maintainers should check off completed items, please do not add/edit items in the list.

## Tracking

https://github.com/exercism/v3-launch/issues/7

**Comment by senekor** [comment]
The remaining items are related to the syllabus, which is currently deactivated. Whatever work needs to be done in the future to create a new syllabus which complies with the spec should be planned & tracked in that context.
